/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppMoradoresRouteImport } from './routes/app.moradores'
import { Route as AppFornecedoresRouteImport } from './routes/app.fornecedores'
import { Route as AppDemandasRouteImport } from './routes/app.demandas'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppBaseRouteImport } from './routes/app.base'
import { Route as AppAgenteRouteImport } from './routes/app.agente'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAmbientesRouteImport } from './routes/admin.ambientes'
import { Route as AppMoradoresIndexRouteImport } from './routes/app.moradores.index'
import { Route as AppFornecedoresIndexRouteImport } from './routes/app.fornecedores.index'
import { Route as AppDemandasIndexRouteImport } from './routes/app.demandas.index'
import { Route as AppBaseIndexRouteImport } from './routes/app.base.index'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin.usuarios.index'
import { Route as AppMoradoresArquivadosRouteImport } from './routes/app.moradores.arquivados'
import { Route as AppMoradoresIdRouteImport } from './routes/app.moradores.$id'
import { Route as AppFornecedoresNovoRouteImport } from './routes/app.fornecedores.novo'
import { Route as AppDemandasNovaRouteImport } from './routes/app.demandas.nova'
import { Route as AppDemandasIdRouteImport } from './routes/app.demandas.$id'
import { Route as AppBaseEnviarRouteImport } from './routes/app.base.enviar'
import { Route as AdminUsuariosNovoRouteImport } from './routes/admin.usuarios.novo'
import { Route as AdminUsuariosIdRouteImport } from './routes/admin.usuarios.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppMoradoresRoute = AppMoradoresRouteImport.update({
  id: '/moradores',
  path: '/moradores',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandasRoute = AppDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseRoute = AppBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmbientesRoute = AdminAmbientesRouteImport.update({
  id: '/ambientes',
  path: '/ambientes',
  getParentRoute: () => AdminRoute,
} as any)
const AppMoradoresIndexRoute = AppMoradoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoradoresRoute,
} as any)
const AppFornecedoresIndexRoute = AppFornecedoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFornecedoresRoute,
} as any)
const AppDemandasIndexRoute = AppDemandasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDemandasRoute,
} as any)
const AppBaseIndexRoute = AppBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBaseRoute,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsuariosRoute,
} as any)
const AppMoradoresArquivadosRoute = AppMoradoresArquivadosRouteImport.update({
  id: '/arquivados',
  path: '/arquivados',
  getParentRoute: () => AppMoradoresRoute,
} as any)
const AppMoradoresIdRoute = AppMoradoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMoradoresRoute,
} as any)
const AppFornecedoresNovoRoute = AppFornecedoresNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppFornecedoresRoute,
} as any)
const AppDemandasNovaRoute = AppDemandasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppDemandasRoute,
} as any)
const AppDemandasIdRoute = AppDemandasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDemandasRoute,
} as any)
const AppBaseEnviarRoute = AppBaseEnviarRouteImport.update({
  id: '/enviar',
  path: '/enviar',
  getParentRoute: () => AppBaseRoute,
} as any)
const AdminUsuariosNovoRoute = AdminUsuariosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminUsuariosRoute,
} as any)
const AdminUsuariosIdRoute = AdminUsuariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsuariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/ambientes': typeof AdminAmbientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/app/agente': typeof AppAgenteRoute
  '/app/base': typeof AppBaseRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/demandas': typeof AppDemandasRouteWithChildren
  '/app/fornecedores': typeof AppFornecedoresRouteWithChildren
  '/app/moradores': typeof AppMoradoresRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/app/base/enviar': typeof AppBaseEnviarRoute
  '/app/demandas/$id': typeof AppDemandasIdRoute
  '/app/demandas/nova': typeof AppDemandasNovaRoute
  '/app/fornecedores/novo': typeof AppFornecedoresNovoRoute
  '/app/moradores/$id': typeof AppMoradoresIdRoute
  '/app/moradores/arquivados': typeof AppMoradoresArquivadosRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/app/base/': typeof AppBaseIndexRoute
  '/app/demandas/': typeof AppDemandasIndexRoute
  '/app/fornecedores/': typeof AppFornecedoresIndexRoute
  '/app/moradores/': typeof AppMoradoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/ambientes': typeof AdminAmbientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/app/base/enviar': typeof AppBaseEnviarRoute
  '/app/demandas/$id': typeof AppDemandasIdRoute
  '/app/demandas/nova': typeof AppDemandasNovaRoute
  '/app/fornecedores/novo': typeof AppFornecedoresNovoRoute
  '/app/moradores/$id': typeof AppMoradoresIdRoute
  '/app/moradores/arquivados': typeof AppMoradoresArquivadosRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
  '/app/base': typeof AppBaseIndexRoute
  '/app/demandas': typeof AppDemandasIndexRoute
  '/app/fornecedores': typeof AppFornecedoresIndexRoute
  '/app/moradores': typeof AppMoradoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/ambientes': typeof AdminAmbientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/app/agente': typeof AppAgenteRoute
  '/app/base': typeof AppBaseRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/demandas': typeof AppDemandasRouteWithChildren
  '/app/fornecedores': typeof AppFornecedoresRouteWithChildren
  '/app/moradores': typeof AppMoradoresRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/app/base/enviar': typeof AppBaseEnviarRoute
  '/app/demandas/$id': typeof AppDemandasIdRoute
  '/app/demandas/nova': typeof AppDemandasNovaRoute
  '/app/fornecedores/novo': typeof AppFornecedoresNovoRoute
  '/app/moradores/$id': typeof AppMoradoresIdRoute
  '/app/moradores/arquivados': typeof AppMoradoresArquivadosRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/app/base/': typeof AppBaseIndexRoute
  '/app/demandas/': typeof AppDemandasIndexRoute
  '/app/fornecedores/': typeof AppFornecedoresIndexRoute
  '/app/moradores/': typeof AppMoradoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/ambientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/usuarios'
    | '/app/agente'
    | '/app/base'
    | '/app/configuracoes'
    | '/app/demandas'
    | '/app/fornecedores'
    | '/app/moradores'
    | '/admin/'
    | '/app/'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/novo'
    | '/app/base/enviar'
    | '/app/demandas/$id'
    | '/app/demandas/nova'
    | '/app/fornecedores/novo'
    | '/app/moradores/$id'
    | '/app/moradores/arquivados'
    | '/admin/usuarios/'
    | '/app/base/'
    | '/app/demandas/'
    | '/app/fornecedores/'
    | '/app/moradores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/admin/ambientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/app/agente'
    | '/app/configuracoes'
    | '/admin'
    | '/app'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/novo'
    | '/app/base/enviar'
    | '/app/demandas/$id'
    | '/app/demandas/nova'
    | '/app/fornecedores/novo'
    | '/app/moradores/$id'
    | '/app/moradores/arquivados'
    | '/admin/usuarios'
    | '/app/base'
    | '/app/demandas'
    | '/app/fornecedores'
    | '/app/moradores'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/ambientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/usuarios'
    | '/app/agente'
    | '/app/base'
    | '/app/configuracoes'
    | '/app/demandas'
    | '/app/fornecedores'
    | '/app/moradores'
    | '/admin/'
    | '/app/'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/novo'
    | '/app/base/enviar'
    | '/app/demandas/$id'
    | '/app/demandas/nova'
    | '/app/fornecedores/novo'
    | '/app/moradores/$id'
    | '/app/moradores/arquivados'
    | '/admin/usuarios/'
    | '/app/base/'
    | '/app/demandas/'
    | '/app/fornecedores/'
    | '/app/moradores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/moradores': {
      id: '/app/moradores'
      path: '/moradores'
      fullPath: '/app/moradores'
      preLoaderRoute: typeof AppMoradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedores': {
      id: '/app/fornecedores'
      path: '/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demandas': {
      id: '/app/demandas'
      path: '/demandas'
      fullPath: '/app/demandas'
      preLoaderRoute: typeof AppDemandasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/base': {
      id: '/app/base'
      path: '/base'
      fullPath: '/app/base'
      preLoaderRoute: typeof AppBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agente': {
      id: '/app/agente'
      path: '/agente'
      fullPath: '/app/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ambientes': {
      id: '/admin/ambientes'
      path: '/ambientes'
      fullPath: '/admin/ambientes'
      preLoaderRoute: typeof AdminAmbientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/moradores/': {
      id: '/app/moradores/'
      path: '/'
      fullPath: '/app/moradores/'
      preLoaderRoute: typeof AppMoradoresIndexRouteImport
      parentRoute: typeof AppMoradoresRoute
    }
    '/app/fornecedores/': {
      id: '/app/fornecedores/'
      path: '/'
      fullPath: '/app/fornecedores/'
      preLoaderRoute: typeof AppFornecedoresIndexRouteImport
      parentRoute: typeof AppFornecedoresRoute
    }
    '/app/demandas/': {
      id: '/app/demandas/'
      path: '/'
      fullPath: '/app/demandas/'
      preLoaderRoute: typeof AppDemandasIndexRouteImport
      parentRoute: typeof AppDemandasRoute
    }
    '/app/base/': {
      id: '/app/base/'
      path: '/'
      fullPath: '/app/base/'
      preLoaderRoute: typeof AppBaseIndexRouteImport
      parentRoute: typeof AppBaseRoute
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
    '/app/moradores/arquivados': {
      id: '/app/moradores/arquivados'
      path: '/arquivados'
      fullPath: '/app/moradores/arquivados'
      preLoaderRoute: typeof AppMoradoresArquivadosRouteImport
      parentRoute: typeof AppMoradoresRoute
    }
    '/app/moradores/$id': {
      id: '/app/moradores/$id'
      path: '/$id'
      fullPath: '/app/moradores/$id'
      preLoaderRoute: typeof AppMoradoresIdRouteImport
      parentRoute: typeof AppMoradoresRoute
    }
    '/app/fornecedores/novo': {
      id: '/app/fornecedores/novo'
      path: '/novo'
      fullPath: '/app/fornecedores/novo'
      preLoaderRoute: typeof AppFornecedoresNovoRouteImport
      parentRoute: typeof AppFornecedoresRoute
    }
    '/app/demandas/nova': {
      id: '/app/demandas/nova'
      path: '/nova'
      fullPath: '/app/demandas/nova'
      preLoaderRoute: typeof AppDemandasNovaRouteImport
      parentRoute: typeof AppDemandasRoute
    }
    '/app/demandas/$id': {
      id: '/app/demandas/$id'
      path: '/$id'
      fullPath: '/app/demandas/$id'
      preLoaderRoute: typeof AppDemandasIdRouteImport
      parentRoute: typeof AppDemandasRoute
    }
    '/app/base/enviar': {
      id: '/app/base/enviar'
      path: '/enviar'
      fullPath: '/app/base/enviar'
      preLoaderRoute: typeof AppBaseEnviarRouteImport
      parentRoute: typeof AppBaseRoute
    }
    '/admin/usuarios/novo': {
      id: '/admin/usuarios/novo'
      path: '/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AdminUsuariosNovoRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
    '/admin/usuarios/$id': {
      id: '/admin/usuarios/$id'
      path: '/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AdminUsuariosIdRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
  }
}

interface AdminUsuariosRouteChildren {
  AdminUsuariosIdRoute: typeof AdminUsuariosIdRoute
  AdminUsuariosNovoRoute: typeof AdminUsuariosNovoRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
}

const AdminUsuariosRouteChildren: AdminUsuariosRouteChildren = {
  AdminUsuariosIdRoute: AdminUsuariosIdRoute,
  AdminUsuariosNovoRoute: AdminUsuariosNovoRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
}

const AdminUsuariosRouteWithChildren = AdminUsuariosRoute._addFileChildren(
  AdminUsuariosRouteChildren,
)

interface AdminRouteChildren {
  AdminAmbientesRoute: typeof AdminAmbientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminUsuariosRoute: typeof AdminUsuariosRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAmbientesRoute: AdminAmbientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminUsuariosRoute: AdminUsuariosRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppBaseRouteChildren {
  AppBaseEnviarRoute: typeof AppBaseEnviarRoute
  AppBaseIndexRoute: typeof AppBaseIndexRoute
}

const AppBaseRouteChildren: AppBaseRouteChildren = {
  AppBaseEnviarRoute: AppBaseEnviarRoute,
  AppBaseIndexRoute: AppBaseIndexRoute,
}

const AppBaseRouteWithChildren =
  AppBaseRoute._addFileChildren(AppBaseRouteChildren)

interface AppDemandasRouteChildren {
  AppDemandasIdRoute: typeof AppDemandasIdRoute
  AppDemandasNovaRoute: typeof AppDemandasNovaRoute
  AppDemandasIndexRoute: typeof AppDemandasIndexRoute
}

const AppDemandasRouteChildren: AppDemandasRouteChildren = {
  AppDemandasIdRoute: AppDemandasIdRoute,
  AppDemandasNovaRoute: AppDemandasNovaRoute,
  AppDemandasIndexRoute: AppDemandasIndexRoute,
}

const AppDemandasRouteWithChildren = AppDemandasRoute._addFileChildren(
  AppDemandasRouteChildren,
)

interface AppFornecedoresRouteChildren {
  AppFornecedoresNovoRoute: typeof AppFornecedoresNovoRoute
  AppFornecedoresIndexRoute: typeof AppFornecedoresIndexRoute
}

const AppFornecedoresRouteChildren: AppFornecedoresRouteChildren = {
  AppFornecedoresNovoRoute: AppFornecedoresNovoRoute,
  AppFornecedoresIndexRoute: AppFornecedoresIndexRoute,
}

const AppFornecedoresRouteWithChildren = AppFornecedoresRoute._addFileChildren(
  AppFornecedoresRouteChildren,
)

interface AppMoradoresRouteChildren {
  AppMoradoresIdRoute: typeof AppMoradoresIdRoute
  AppMoradoresArquivadosRoute: typeof AppMoradoresArquivadosRoute
  AppMoradoresIndexRoute: typeof AppMoradoresIndexRoute
}

const AppMoradoresRouteChildren: AppMoradoresRouteChildren = {
  AppMoradoresIdRoute: AppMoradoresIdRoute,
  AppMoradoresArquivadosRoute: AppMoradoresArquivadosRoute,
  AppMoradoresIndexRoute: AppMoradoresIndexRoute,
}

const AppMoradoresRouteWithChildren = AppMoradoresRoute._addFileChildren(
  AppMoradoresRouteChildren,
)

interface AppRouteChildren {
  AppAgenteRoute: typeof AppAgenteRoute
  AppBaseRoute: typeof AppBaseRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDemandasRoute: typeof AppDemandasRouteWithChildren
  AppFornecedoresRoute: typeof AppFornecedoresRouteWithChildren
  AppMoradoresRoute: typeof AppMoradoresRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenteRoute: AppAgenteRoute,
  AppBaseRoute: AppBaseRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDemandasRoute: AppDemandasRouteWithChildren,
  AppFornecedoresRoute: AppFornecedoresRouteWithChildren,
  AppMoradoresRoute: AppMoradoresRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
