/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMoradoresRouteImport } from './routes/app.moradores'
import { Route as AppFornecedoresRouteImport } from './routes/app.fornecedores'
import { Route as AppDemandasRouteImport } from './routes/app.demandas'
import { Route as AppBaseRouteImport } from './routes/app.base'
import { Route as AppAgenteRouteImport } from './routes/app.agente'
import { Route as AppDemandasIdRouteImport } from './routes/app.demandas.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoradoresRoute = AppMoradoresRouteImport.update({
  id: '/moradores',
  path: '/moradores',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandasRoute = AppDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseRoute = AppBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandasIdRoute = AppDemandasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDemandasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/base': typeof AppBaseRoute
  '/app/demandas': typeof AppDemandasRouteWithChildren
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/moradores': typeof AppMoradoresRoute
  '/app/': typeof AppIndexRoute
  '/app/demandas/$id': typeof AppDemandasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/base': typeof AppBaseRoute
  '/app/demandas': typeof AppDemandasRouteWithChildren
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/moradores': typeof AppMoradoresRoute
  '/app': typeof AppIndexRoute
  '/app/demandas/$id': typeof AppDemandasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agente': typeof AppAgenteRoute
  '/app/base': typeof AppBaseRoute
  '/app/demandas': typeof AppDemandasRouteWithChildren
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/moradores': typeof AppMoradoresRoute
  '/app/': typeof AppIndexRoute
  '/app/demandas/$id': typeof AppDemandasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agente'
    | '/app/base'
    | '/app/demandas'
    | '/app/fornecedores'
    | '/app/moradores'
    | '/app/'
    | '/app/demandas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/agente'
    | '/app/base'
    | '/app/demandas'
    | '/app/fornecedores'
    | '/app/moradores'
    | '/app'
    | '/app/demandas/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agente'
    | '/app/base'
    | '/app/demandas'
    | '/app/fornecedores'
    | '/app/moradores'
    | '/app/'
    | '/app/demandas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moradores': {
      id: '/app/moradores'
      path: '/moradores'
      fullPath: '/app/moradores'
      preLoaderRoute: typeof AppMoradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedores': {
      id: '/app/fornecedores'
      path: '/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demandas': {
      id: '/app/demandas'
      path: '/demandas'
      fullPath: '/app/demandas'
      preLoaderRoute: typeof AppDemandasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/base': {
      id: '/app/base'
      path: '/base'
      fullPath: '/app/base'
      preLoaderRoute: typeof AppBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agente': {
      id: '/app/agente'
      path: '/agente'
      fullPath: '/app/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demandas/$id': {
      id: '/app/demandas/$id'
      path: '/$id'
      fullPath: '/app/demandas/$id'
      preLoaderRoute: typeof AppDemandasIdRouteImport
      parentRoute: typeof AppDemandasRoute
    }
  }
}

interface AppDemandasRouteChildren {
  AppDemandasIdRoute: typeof AppDemandasIdRoute
}

const AppDemandasRouteChildren: AppDemandasRouteChildren = {
  AppDemandasIdRoute: AppDemandasIdRoute,
}

const AppDemandasRouteWithChildren = AppDemandasRoute._addFileChildren(
  AppDemandasRouteChildren,
)

interface AppRouteChildren {
  AppAgenteRoute: typeof AppAgenteRoute
  AppBaseRoute: typeof AppBaseRoute
  AppDemandasRoute: typeof AppDemandasRouteWithChildren
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppMoradoresRoute: typeof AppMoradoresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenteRoute: AppAgenteRoute,
  AppBaseRoute: AppBaseRoute,
  AppDemandasRoute: AppDemandasRouteWithChildren,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppMoradoresRoute: AppMoradoresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
